coverage:
  precision: 2
  round: nearest
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 0%
        base: auto
