# MakeMKV Auto Rip Configuration
# This file contains all configuration settings for the application
# Paths are automatically normalized for the current operating system

# Application paths and directories
paths:
  # MakeMKV installation directory
  makemkv_dir: "C:/Program Files (x86)/MakeMKV"
  # Directory where ripped movies/tv/media will be saved
  movie_rips_dir: "./media"

  # Logging configuration
  logging:
    # Whether to save logs to files (true/false)
    enabled: true
    # Directory where log files will be saved
    dir: "./logs"
    # Time format for log timestamps (12hr/24hr)
    time_format: "12hr"

# Drive operation settings
drives:
  # Automatically load/mount optical drives (true/false)
  auto_load: true
  # Automatically eject drives after ripping (true/false)
  auto_eject: true

# Ripping behavior settings
ripping:
  # Rip all titles (over the MakeMKV minimum length) from disc instead of just the longest title (true/false)
  rip_all_titles: false
  # Ripping mode - async for parallel processing, sync for sequential (async/sync)
  mode: "async"
