name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce this behavior.
      placeholder: |
        1. Go to...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - Linux (specify in additional context)
        - macOS (specify in additional context)
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running? (run `node --version`)
      placeholder: "v22.0.0"
    validations:
      required: true

  - type: input
    id: makemkv-version
    attributes:
      label: MakeMKV Version
      description: What version of MakeMKV do you have installed?
      placeholder: "1.17.x"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant parts of your config/default.json (remove sensitive paths)
      render: json
      placeholder: |
        {
          "Path": {
            "mkvDir": {
              "Dir": "C:\\Program Files (x86)\\MakeMKV"
            },
            "movieRips": {
              "Dir": "C:\\Your\\Path"
            }
          }
        }

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Any error messages or relevant output
      render: shell
      placeholder: Paste any error messages or relevant output here...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might help...
